### ISSUE TITLE
move to trash not working

### ISSUE THREAD

**Issue by support-xylusthemes** [xylusthemes/wp-bulk-delete#10]
I wanted to delete a custom post type and move it to trash.
- starting to delete art-exhibitions: there are 7734
- used option move to trash
- limit 3
- result: there are 3 less art-exhibitions (should be the same amount as the deleted should be in the trash): Art-Exhibitions (7728 Art-Exhibitions)
(count is 6 less, that is presumably because we are using wpml and the translation is deleted as well)
- trash is empty
so the custom posts were deleted! I expected to find them in the trash.

**Comment by Rajat1192** [comment]
This bug is resolved in the plugin's latest version
